# https://docs.docker.com/compose/compose-file/05-services/
services:
  django:
    # TODO -- put the sqlite database someplace outside the container!
    build:
      context: .
    environment:
      DJANGO_SECRET_FILE: /run/secrets/django_secret
    secrets:
      - django_secret

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # host:container
      - '8080:80' # Public HTTP Port
      - '4430:443' # Public HTTPS Port
      - '8100:81' # Admin Web Port

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

secrets:
  django_secret:
    environment: "SECRET_KEY"
