services:
  django:
    build:
      context: .
    environment:
      SECRET_KEY: not-really-secret

  web:
    image: nginx
    ports:
     - "8080:80"
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
