# https://docs.docker.com/compose/compose-file/05-services/
services:
  django:
    # TODO -- put the sqlite database someplace outside the container!
    build:
      context: .
    environment:
      DJANGO_SECRET_FILE: /run/secrets/django_secret
    init: true                  # https://docs.docker.com/reference/compose-file/services/#init
    secrets:
      - django_secret

secrets:
  # TODO -- recaptcha secret too
  django_secret:
    environment: "SECRET_KEY"
