services:
  django:
    build:
      context: .
    environment:
      DJANGO_SECRET_FILE: /run/secrets/django_secret
    secrets:
      - django_secret

  web:
    image: nginx
    ports:
     - "8080:80"
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf

secrets:
  django_secret:
    environment: "DJANGO_SECRET"
