volumes:
  caddy_data: {}
  sqlite_data: {}

# https://docs.docker.com/compose/compose-file/05-services/
services:
  caddy:
    # Unlike the official caddy image, this is falling-down-easy to configure as a lets-encrypt-certificate-fetching
    # reverse proxy.
    # https://github.com/lucaslorentz/caddy-docker-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    profiles:
      - prod

  django:
    build:
      context: .
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DJANGO_SECRET_FILE: /run/secrets/django_secret
      SQLITE_DATA_DIR: /data
    init: true                  # https://docs.docker.com/reference/compose-file/services/#init
    labels:
      caddy: ${CADDY_HOSTNAME:-}
      caddy.reverse_proxy: "{{upstreams 8000}}"
    ports:
      - "127.0.0.1:8000:8000"
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
      - django_secret
    volumes:
      - sqlite_data:/data

secrets:
  # TODO -- recaptcha secret too
  aws_access_key_id:
    environment: AWS_ACCESS_KEY_ID
  aws_secret_access_key:
    environment: AWS_SECRET_ACCESS_KEY
  django_secret:
    environment: "DJANGO_SECRET_KEY"
