[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "tinyurl"
version = "0.0"
description = "wat"
authors = ["Eric Hanchrow <eric.hanchrow@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.26.22"
pyramid = "^2.0"
pyramid-debugtoolbar = "^4.9"
pyramid-tm = "^2.5"
transaction = "^3.0.1"
waitress = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
