# Generated by Django 5.0.6 on 2024-07-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('short', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('original', models.CharField(max_length=1024)),
            ],
        ),
    ]
