# Generated by Django 5.0.6 on 2024-07-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shortenedurl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
