# Generated by Django 5.0.6 on 2024-07-07 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shortenedurl_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
