# Generated by Django 5.0.6 on 2024-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shortenedurl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original',
            field=models.URLField(max_length=1024),
        ),
    ]
